// ─── Interfaces ───────────────────────────────────────────────────────────────

export interface TopicPerformance {
  id: string;
  name: string;
  code: string;
  proficiency: number; // 0 - 100
  totalQuestions: number;
  accuracy: number;
  trend: 'up' | 'down' | 'neutral';
  color: string;
}

export interface RecentAssessment {
  id: string;
  title: string;
  subject: string;
  date: string;
  score: number;
  questionsCount: number;
  abilityScore: number;
  status: 'completed' | 'in_progress';
}

export interface AbilityDataPoint {
  questionNumber: string;
  ability: number;
  difficulty: number;
  topic: string;
  correct: boolean;
}

export interface AssessmentQuestion {
  id: string;
  topic: string;         // "DSA" | "DBMS" | "OS" | "CN"
  subtopic: string;
  difficultyLabel: string;
  difficultyLevel: number; // 1–5
  questionText: string;
  options: string[];
  correctOptionIndex: number;
  explanation: string;
}

export interface AdminQuestionItem {
  id: string;
  topic: string;
  subtopic: string;
  difficulty: string;
  difficultyLevel: number;
  questionText: string;
  options: string[];
  correctOptionIndex: number;
  status: "pending" | "approved" | "rejected";
  sourceLabel: string;
}

// ─── Demo Student ─────────────────────────────────────────────────────────────

export const MOCK_STUDENT = {
  name: "Demo Student",
  email: "demo@parakh.edu",
  avatarUrl: "",
  rollNumber: "DEMO-001",
  overallProficiency: 72,
  estimatedAbilityLevel: "Intermediate",
  assessmentsCompleted: 6,
  totalQuestionsAnswered: 52,
  avgResponseTimeSec: 38,
};

// ─── Topics ───────────────────────────────────────────────────────────────────

export const MOCK_TOPICS: TopicPerformance[] = [
  {
    id: "dsa",
    name: "Data Structures & Algorithms",
    code: "DSA",
    proficiency: 82,
    totalQuestions: 20,
    accuracy: 80,
    trend: "up",
    color: "#6366f1",
  },
  {
    id: "os",
    name: "Operating Systems",
    code: "OS",
    proficiency: 74,
    totalQuestions: 15,
    accuracy: 73,
    trend: "up",
    color: "#06b6d4",
  },
  {
    id: "dbms",
    name: "Database Management Systems",
    code: "DBMS",
    proficiency: 60,
    totalQuestions: 12,
    accuracy: 58,
    trend: "down",
    color: "#f59e0b",
  },
  {
    id: "cn",
    name: "Computer Networks",
    code: "CN",
    proficiency: 55,
    totalQuestions: 10,
    accuracy: 54,
    trend: "neutral",
    color: "#ec4899",
  },
];

// ─── Demo Assessment History ──────────────────────────────────────────────────

export const MOCK_RECENT_ASSESSMENTS: RecentAssessment[] = [
  {
    id: "sess-001",
    title: "Mixed Adaptive Session",
    subject: "Mixed",
    date: "Today",
    score: 78,
    questionsCount: 10,
    abilityScore: 72,
    status: "completed",
  },
  {
    id: "sess-002",
    title: "DBMS Focus Drill",
    subject: "DBMS",
    date: "Yesterday",
    score: 60,
    questionsCount: 5,
    abilityScore: 58,
    status: "completed",
  },
  {
    id: "sess-003",
    title: "DSA Practice",
    subject: "DSA",
    date: "2 days ago",
    score: 85,
    questionsCount: 10,
    abilityScore: 82,
    status: "completed",
  },
  {
    id: "sess-004",
    title: "OS Synchronization",
    subject: "OS",
    date: "4 days ago",
    score: 70,
    questionsCount: 5,
    abilityScore: 68,
    status: "completed",
  },
];

// ─── Ability Trajectory (demo history for analytics page) ────────────────────

export const MOCK_ABILITY_TRAJECTORY: AbilityDataPoint[] = [
  { questionNumber: "Q1", ability: 50, difficulty: 2, topic: "DSA", correct: true },
  { questionNumber: "Q2", ability: 58, difficulty: 3, topic: "DBMS", correct: true },
  { questionNumber: "Q3", ability: 64, difficulty: 3, topic: "OS", correct: true },
  { questionNumber: "Q4", ability: 72, difficulty: 4, topic: "DSA", correct: true },
  { questionNumber: "Q5", ability: 66, difficulty: 4, topic: "DBMS", correct: false },
  { questionNumber: "Q6", ability: 73, difficulty: 3, topic: "CN", correct: true },
  { questionNumber: "Q7", ability: 80, difficulty: 4, topic: "OS", correct: true },
  { questionNumber: "Q8", ability: 74, difficulty: 5, topic: "DSA", correct: false },
  { questionNumber: "Q9", ability: 79, difficulty: 4, topic: "DBMS", correct: true },
  { questionNumber: "Q10", ability: 83, difficulty: 4, topic: "DSA", correct: true },
];

// ─── Demo Insights ────────────────────────────────────────────────────────────

export const MOCK_STRENGTHS = [
  {
    topic: "Data Structures",
    detail: "Strong accuracy on tree traversal and graph problems.",
  },
  {
    topic: "OS Memory Management",
    detail: "Consistent performance on paging and virtual memory questions.",
  },
];

export const MOCK_AREAS_TO_IMPROVE = [
  {
    topic: "DBMS Normalization",
    detail: "Lower accuracy on 3NF vs BCNF dependency questions.",
    recommendedAction: "Review functional dependency rules.",
  },
  {
    topic: "Computer Networks",
    detail: "TCP congestion control and sliding window protocols.",
    recommendedAction: "Practice flow control problem sets.",
  },
];

// ─── Question Bank (120 questions total: 30 each for DSA, DBMS, OS, CN) ────────

export const QUESTION_BANK: AssessmentQuestion[] = [
  // ── DSA (30 Questions) ──────────────────────────────────────────────────────
  {
    id: "dsa-1",
    topic: "DSA",
    subtopic: "Arrays",
    difficultyLabel: "Easy",
    difficultyLevel: 1,
    questionText: "What is the time complexity of accessing an element in an array by index?",
    options: ["O(n)", "O(log n)", "O(1)", "O(n²)"],
    correctOptionIndex: 2,
    explanation: "Array elements are stored in contiguous memory. Accessing by index computes the address directly, giving O(1) constant time.",
  },
  {
    id: "dsa-2",
    topic: "DSA",
    subtopic: "Linked Lists",
    difficultyLabel: "Easy",
    difficultyLevel: 2,
    questionText: "In a singly linked list, which operation is O(1) when performed at the head?",
    options: ["Deletion at tail", "Insertion at head", "Searching for a value", "Reversing the list"],
    correctOptionIndex: 1,
    explanation: "Insertion at the head only requires updating the head pointer, which takes O(1). All other options require traversal.",
  },
  {
    id: "dsa-3",
    topic: "DSA",
    subtopic: "Binary Trees",
    difficultyLabel: "Medium",
    difficultyLevel: 3,
    questionText: "Which traversal of a Binary Search Tree produces keys in sorted ascending order?",
    options: ["Pre-order", "In-order", "Post-order", "Level-order"],
    correctOptionIndex: 1,
    explanation: "In-order traversal (Left → Root → Right) visits BST nodes in non-decreasing order because every left subtree contains smaller keys.",
  },
  {
    id: "dsa-4",
    topic: "DSA",
    subtopic: "Sorting",
    difficultyLabel: "Medium",
    difficultyLevel: 3,
    questionText: "Which sorting algorithm has the best average-case time complexity?",
    options: ["Bubble Sort — O(n²)", "Merge Sort — O(n log n)", "Insertion Sort — O(n²)", "Selection Sort — O(n²)"],
    correctOptionIndex: 1,
    explanation: "Merge Sort divides the array recursively and merges in O(n) per level, giving O(n log n) average and worst-case complexity.",
  },
  {
    id: "dsa-5",
    topic: "DSA",
    subtopic: "Graph Algorithms",
    difficultyLabel: "Hard",
    difficultyLevel: 4,
    questionText: "What is the worst-case time complexity of Dijkstra's algorithm using a Min-Heap?",
    options: ["O(V²)", "O((V + E) log V)", "O(V × E)", "O(E log E)"],
    correctOptionIndex: 1,
    explanation: "With a binary min-heap, each vertex is extracted once (O(V log V)) and each edge is relaxed once (O(E log V)), giving O((V + E) log V) total.",
  },
  {
    id: "dsa-6",
    topic: "DSA",
    subtopic: "Dynamic Programming",
    difficultyLabel: "Very Hard",
    difficultyLevel: 5,
    questionText: "In the 0/1 Knapsack problem with n items and capacity W, the standard DP solution has time complexity:",
    options: ["O(n log n)", "O(n + W)", "O(n × W)", "O(2ⁿ)"],
    correctOptionIndex: 2,
    explanation: "The DP table has n rows and W+1 columns. Filling each cell takes O(1), so the total is O(n × W) — pseudo-polynomial time.",
  },
  {
    id: "dsa-7",
    topic: "DSA",
    subtopic: "Stacks & Queues",
    difficultyLabel: "Easy",
    difficultyLevel: 1,
    questionText: "Which data structure operates on a Last-In, First-Out (LIFO) basis?",
    options: ["Queue", "Stack", "Array", "Binary Tree"],
    correctOptionIndex: 1,
    explanation: "A Stack is a LIFO data structure where elements pushed last are popped first.",
  },
  {
    id: "dsa-8",
    topic: "DSA",
    subtopic: "Stacks & Queues",
    difficultyLabel: "Easy",
    difficultyLevel: 1,
    questionText: "Which data structure operates on a First-In, First-Out (FIFO) basis?",
    options: ["Stack", "Queue", "Heap", "Graph"],
    correctOptionIndex: 1,
    explanation: "A Queue processes elements in First-In, First-Out (FIFO) order.",
  },
  {
    id: "dsa-9",
    topic: "DSA",
    subtopic: "Searching",
    difficultyLabel: "Easy",
    difficultyLevel: 2,
    questionText: "What prerequisite must be met to perform Binary Search on an array?",
    options: ["Array must be dynamically sized", "Array elements must be sorted", "Array must contain only positive integers", "Array must have even length"],
    correctOptionIndex: 1,
    explanation: "Binary search repeatedly divides the search space in half, which relies on elements being sorted.",
  },
  {
    id: "dsa-10",
    topic: "DSA",
    subtopic: "Hash Tables",
    difficultyLabel: "Easy",
    difficultyLevel: 2,
    questionText: "In Hash Tables, separate chaining resolves collisions by using:",
    options: ["Open addressing with linear probing", "Linked lists at each hash bucket", "Re-hashing with a second hash function", "Resizing the array immediately"],
    correctOptionIndex: 1,
    explanation: "Separate chaining maintains a linked list (or dynamic list) at each bucket index to hold colliding elements.",
  },
  {
    id: "dsa-11",
    topic: "DSA",
    subtopic: "Linked Lists",
    difficultyLabel: "Easy",
    difficultyLevel: 2,
    questionText: "What is the time complexity of deleting a node when given a direct pointer to that node in a Doubly Linked List?",
    options: ["O(n)", "O(1)", "O(log n)", "O(n²)"],
    correctOptionIndex: 1,
    explanation: "In a Doubly Linked List, having a direct pointer allows updating prev.next and next.prev in O(1) constant time without traversal.",
  },
  {
    id: "dsa-12",
    topic: "DSA",
    subtopic: "Binary Trees",
    difficultyLabel: "Medium",
    difficultyLevel: 3,
    questionText: "What is the maximum space complexity of recursive DFS on a binary tree of height h?",
    options: ["O(1)", "O(h)", "O(2ʰ)", "O(n log n)"],
    correctOptionIndex: 1,
    explanation: "Recursive DFS pushes stack frames for each call along the current path, requiring memory proportional to tree height O(h).",
  },
  {
    id: "dsa-13",
    topic: "DSA",
    subtopic: "Heaps",
    difficultyLabel: "Medium",
    difficultyLevel: 3,
    questionText: "What is the time complexity of building a Binary Heap from an unsorted array of size n (Build-Heap)?",
    options: ["O(n log n)", "O(n)", "O(n²)", "O(log n)"],
    correctOptionIndex: 1,
    explanation: "Using bottom-up heapify for all internal nodes mathematically converges to O(n) linear time.",
  },
  {
    id: "dsa-14",
    topic: "DSA",
    subtopic: "Graph Algorithms",
    difficultyLabel: "Medium",
    difficultyLevel: 3,
    questionText: "Breadth-First Search (BFS) on an unweighted graph guarantees finding:",
    options: ["The longest simple path", "The shortest path in terms of edge count", "The minimum spanning tree", "The strongly connected components"],
    correctOptionIndex: 1,
    explanation: "BFS explores nodes level-by-level, ensuring the first time a target node is visited corresponds to the shortest path in unweighted graphs.",
  },
  {
    id: "dsa-15",
    topic: "DSA",
    subtopic: "Graph Algorithms",
    difficultyLabel: "Medium",
    difficultyLevel: 3,
    questionText: "Which graph traversal mechanism uses a Queue data structure?",
    options: ["Depth-First Search (DFS)", "Breadth-First Search (BFS)", "Pre-order Traversal", "Backtracking"],
    correctOptionIndex: 1,
    explanation: "BFS uses a FIFO queue to explore vertices level by level.",
  },
  {
    id: "dsa-16",
    topic: "DSA",
    subtopic: "Sorting & Searching",
    difficultyLabel: "Medium",
    difficultyLevel: 3,
    questionText: "What is the average-case time complexity of QuickSelect to find the k-th smallest element in an array?",
    options: ["O(n²)", "O(n log n)", "O(n)", "O(log n)"],
    correctOptionIndex: 2,
    explanation: "QuickSelect partitions the array like QuickSort but recurses only into the partition containing index k, achieving O(n) average time.",
  },
  {
    id: "dsa-17",
    topic: "DSA",
    subtopic: "Balanced Trees",
    difficultyLabel: "Medium",
    difficultyLevel: 3,
    questionText: "In an AVL tree, what is the maximum allowed difference in height between left and right subtrees for any node?",
    options: ["0", "1", "2", "log n"],
    correctOptionIndex: 1,
    explanation: "AVL trees maintain height balance factor in {-1, 0, +1}. A difference > 1 triggers rotations.",
  },
  {
    id: "dsa-18",
    topic: "DSA",
    subtopic: "Advanced Data Structures",
    difficultyLabel: "Medium",
    difficultyLevel: 3,
    questionText: "Searching for a word of length L in a Trie data structure takes time:",
    options: ["O(n)", "O(L)", "O(n log n)", "O(2ᴸ)"],
    correctOptionIndex: 1,
    explanation: "A Trie follows characters one by one, performing L character lookups regardless of the total number of words n stored.",
  },
  {
    id: "dsa-19",
    topic: "DSA",
    subtopic: "Graph Algorithms",
    difficultyLabel: "Medium",
    difficultyLevel: 3,
    questionText: "Topological Sort can be performed on which type of graph?",
    options: ["Undirected Acyclic Graph", "Directed Acyclic Graph (DAG)", "Complete Graph", "Bipartite Graph"],
    correctOptionIndex: 1,
    explanation: "Topological ordering requires directed edges without cycles (DAG); cycles create contradictory dependency loops.",
  },
  {
    id: "dsa-20",
    topic: "DSA",
    subtopic: "Graph Algorithms",
    difficultyLabel: "Hard",
    difficultyLevel: 4,
    questionText: "What is the time complexity of Kruskal's algorithm to find Minimum Spanning Tree using Disjoint Set Union (DSU)?",
    options: ["O(V²)", "O(E log E)", "O(V × E)", "O(V + E)"],
    correctOptionIndex: 1,
    explanation: "Kruskal's algorithm sorts E edges in O(E log E) time. DSU operations take near O(1) amortized time, so sorting dominates.",
  },
  {
    id: "dsa-21",
    topic: "DSA",
    subtopic: "Graph Algorithms",
    difficultyLabel: "Hard",
    difficultyLevel: 4,
    questionText: "Prim's MST algorithm implemented with an Adjacency Matrix runs in time:",
    options: ["O(V²)", "O(E log V)", "O(V log V)", "O(V³)"],
    correctOptionIndex: 0,
    explanation: "Using an adjacency matrix, finding the minimum key node takes O(V) per step across V iterations, resulting in O(V²) time.",
  },
  {
    id: "dsa-22",
    topic: "DSA",
    subtopic: "Dynamic Programming",
    difficultyLabel: "Hard",
    difficultyLevel: 4,
    questionText: "The Floyd-Warshall algorithm computes all-pairs shortest paths in time complexity:",
    options: ["O(V² log V)", "O(V³)", "O(V × E)", "O(E²)"],
    correctOptionIndex: 1,
    explanation: "Floyd-Warshall uses three nested loops over all vertices, giving O(V³) time complexity.",
  },
  {
    id: "dsa-23",
    topic: "DSA",
    subtopic: "Graph Algorithms",
    difficultyLabel: "Hard",
    difficultyLevel: 4,
    questionText: "Which shortest path algorithm can detect negative weight cycles in a graph?",
    options: ["Dijkstra's Algorithm", "Bellman-Ford Algorithm", "BFS", "Prim's Algorithm"],
    correctOptionIndex: 1,
    explanation: "Bellman-Ford relaxes edges V-1 times. Running a V-th relaxation pass detects negative cycles if any distance decreases.",
  },
  {
    id: "dsa-24",
    topic: "DSA",
    subtopic: "Advanced Data Structures",
    difficultyLabel: "Hard",
    difficultyLevel: 4,
    questionText: "In a Segment Tree built for range sum queries over an array of size n, point update operation takes time:",
    options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"],
    correctOptionIndex: 1,
    explanation: "A segment tree has height O(log n). Updating a single point updates one path from leaf to root in O(log n) time.",
  },
  {
    id: "dsa-25",
    topic: "DSA",
    subtopic: "Disjoint Sets",
    difficultyLabel: "Hard",
    difficultyLevel: 4,
    questionText: "Disjoint Set Union (DSU) using path compression and union by rank has an amortized time complexity per operation of:",
    options: ["O(log n)", "O(α(n))", "O(1)", "O(n)"],
    correctOptionIndex: 1,
    explanation: "Using path compression and union by rank yields O(α(n)) amortized time per operation, where α is the inverse Ackermann function (effectively constant < 5).",
  },
  {
    id: "dsa-26",
    topic: "DSA",
    subtopic: "Balanced Trees",
    difficultyLabel: "Hard",
    difficultyLevel: 4,
    questionText: "What is the maximum height of a Red-Black tree with n internal nodes?",
    options: ["log₂ n", "2 log₂(n + 1)", "n / 2", "sqrt(n)"],
    correctOptionIndex: 1,
    explanation: "Properties of Red-Black trees guarantee that no path is more than twice as long as any other path, bounding height to 2 log₂(n + 1).",
  },
  {
    id: "dsa-27",
    topic: "DSA",
    subtopic: "Dynamic Programming",
    difficultyLabel: "Very Hard",
    difficultyLevel: 5,
    questionText: "What is the minimum auxiliary space complexity required to compute the length of the Longest Common Subsequence (LCS) of two strings of lengths m and n?",
    options: ["O(m × n)", "O(min(m, n))", "O(m + n)", "O(1)"],
    correctOptionIndex: 1,
    explanation: "Computing just the length of LCS requires keeping only the current and previous rows/columns in DP, reducing space to O(min(m, n)).",
  },
  {
    id: "dsa-28",
    topic: "DSA",
    subtopic: "String Matching",
    difficultyLabel: "Very Hard",
    difficultyLevel: 5,
    questionText: "The Knuth-Morris-Pratt (KMP) string matching algorithm precomputes the Prefix Function (LPS table) for pattern P of length m in time:",
    options: ["O(m²)", "O(m)", "O(m log m)", "O(2ᵐ)"],
    correctOptionIndex: 1,
    explanation: "Building the Longest Prefix Suffix (LPS) table in KMP uses amortized analysis to run in O(m) linear time.",
  },
  {
    id: "dsa-29",
    topic: "DSA",
    subtopic: "NP-Hard Algorithms",
    difficultyLabel: "Very Hard",
    difficultyLevel: 5,
    questionText: "The Held-Karp Dynamic Programming solution for the Travelling Salesperson Problem (TSP) with n vertices has time complexity:",
    options: ["O(n!)", "O(n² 2ⁿ)", "O(2ⁿ)", "O(n³)"],
    correctOptionIndex: 1,
    explanation: "Held-Karp reduces TSP brute force O(n!) to O(n² 2ⁿ) using bitmask DP state storage.",
  },
  {
    id: "dsa-30",
    topic: "DSA",
    subtopic: "Network Flow",
    difficultyLabel: "Very Hard",
    difficultyLevel: 5,
    questionText: "The Edmonds-Karp algorithm for Maximum Flow uses BFS to find augmenting paths and has time complexity:",
    options: ["O(V² E)", "O(V E²)", "O(V³)", "O(E log V)"],
    correctOptionIndex: 1,
    explanation: "Edmonds-Karp uses BFS for shortest augmenting paths in residual graphs, yielding O(V E²) upper bound time complexity.",
  },

  // ── DBMS (30 Questions) ─────────────────────────────────────────────────────
  {
    id: "dbms-1",
    topic: "DBMS",
    subtopic: "Basics",
    difficultyLabel: "Easy",
    difficultyLevel: 1,
    questionText: "Which SQL command is used to retrieve data from a database table?",
    options: ["INSERT", "UPDATE", "SELECT", "DELETE"],
    correctOptionIndex: 2,
    explanation: "SELECT is the SQL Data Query Language (DQL) command used to fetch data from one or more tables based on specified conditions.",
  },
  {
    id: "dbms-2",
    topic: "DBMS",
    subtopic: "Keys",
    difficultyLabel: "Easy",
    difficultyLevel: 2,
    questionText: "A Primary Key in a relational database must be:",
    options: ["Nullable and unique", "Unique and not null", "Duplicate across rows", "A foreign key from another table"],
    correctOptionIndex: 1,
    explanation: "A Primary Key uniquely identifies each row. It must be unique (no two rows share the same value) and NOT NULL (every row must have a value).",
  },
  {
    id: "dbms-3",
    topic: "DBMS",
    subtopic: "Normalization",
    difficultyLabel: "Medium",
    difficultyLevel: 3,
    questionText: "Which normal form removes transitive functional dependencies of non-prime attributes?",
    options: ["1NF", "2NF", "3NF", "BCNF"],
    correctOptionIndex: 2,
    explanation: "Third Normal Form (3NF) requires the relation to be in 2NF with no non-prime attribute transitively dependent on any candidate key.",
  },
  {
    id: "dbms-4",
    topic: "DBMS",
    subtopic: "Concurrency Control",
    difficultyLabel: "Hard",
    difficultyLevel: 4,
    questionText: "Which locking protocol prevents cascading rollbacks by releasing exclusive locks only at commit/abort?",
    options: ["2-Phase Locking (2PL)", "Strict 2PL", "Basic Timestamp Ordering", "Optimistic Concurrency Control"],
    correctOptionIndex: 1,
    explanation: "Strict 2PL holds all exclusive locks until the transaction commits or aborts, ensuring dirty data is never read by other transactions.",
  },
  {
    id: "dbms-5",
    topic: "DBMS",
    subtopic: "Normalization",
    difficultyLabel: "Very Hard",
    difficultyLevel: 5,
    questionText: "Which condition must hold for a relation to be in Boyce-Codd Normal Form (BCNF)?",
    options: [
      "Every non-prime attribute is fully dependent on the primary key",
      "For every non-trivial FD X → Y, X must be a superkey",
      "There are no multi-valued dependencies",
      "All foreign keys reference valid primary keys"
    ],
    correctOptionIndex: 1,
    explanation: "BCNF requires that for every non-trivial functional dependency X → Y, X must be a superkey. This is stricter than 3NF.",
  },
  {
    id: "dbms-6",
    topic: "DBMS",
    subtopic: "SQL",
    difficultyLabel: "Easy",
    difficultyLevel: 1,
    questionText: "Which SQL clause is used to filter group results generated by GROUP BY?",
    options: ["WHERE", "HAVING", "ORDER BY", "FILTER"],
    correctOptionIndex: 1,
    explanation: "HAVING filters aggregated groups, whereas WHERE filters individual rows before grouping.",
  },
  {
    id: "dbms-7",
    topic: "DBMS",
    subtopic: "SQL Commands",
    difficultyLabel: "Easy",
    difficultyLevel: 1,
    questionText: "Which DDL command is used to remove an entire table structure and data from a database?",
    options: ["DELETE", "TRUNCATE", "DROP", "REMOVE"],
    correctOptionIndex: 2,
    explanation: "DROP TABLE deletes the schema definition along with all rows permanently.",
  },
  {
    id: "dbms-8",
    topic: "DBMS",
    subtopic: "Relational Concepts",
    difficultyLabel: "Easy",
    difficultyLevel: 2,
    questionText: "What is a Super Key in a relational database?",
    options: [
      "A key containing only one column",
      "A set of one or more attributes that uniquely identifies a row in a table",
      "A foreign key that points to a primary key",
      "An attribute with no null values"
    ],
    correctOptionIndex: 1,
    explanation: "A Super Key is any attribute set that uniquely identifies tuples. A Candidate Key is a minimal Super Key.",
  },
  {
    id: "dbms-9",
    topic: "DBMS",
    subtopic: "Integrity Constraints",
    difficultyLabel: "Easy",
    difficultyLevel: 2,
    questionText: "Referential Integrity constraint is maintained using:",
    options: ["Primary Key", "Foreign Key", "Check Constraint", "Unique Key"],
    correctOptionIndex: 1,
    explanation: "Foreign Keys enforce referential integrity by ensuring relationships between records remain valid.",
  },
  {
    id: "dbms-10",
    topic: "DBMS",
    subtopic: "Normalization",
    difficultyLabel: "Easy",
    difficultyLevel: 2,
    questionText: "A relation is in First Normal Form (1NF) if:",
    options: [
      "All attributes are atomic with no repeating groups",
      "There are no partial functional dependencies",
      "There are no transitive dependencies",
      "For X → Y, X is a superkey"
    ],
    correctOptionIndex: 0,
    explanation: "1NF requires attribute values to be atomic (indivisible) and prohibits multi-valued or composite attributes.",
  },
  {
    id: "dbms-11",
    topic: "DBMS",
    subtopic: "Transactions",
    difficultyLabel: "Easy",
    difficultyLevel: 2,
    questionText: "Which ACID property guarantees that all operations within a transaction complete successfully or none are applied?",
    options: ["Consistency", "Atomicity", "Isolation", "Durability"],
    correctOptionIndex: 1,
    explanation: "Atomicity ('all-or-nothing') guarantees that partial transaction execution never persists.",
  },
  {
    id: "dbms-12",
    topic: "DBMS",
    subtopic: "Normalization",
    difficultyLabel: "Medium",
    difficultyLevel: 3,
    questionText: "A relation is in Second Normal Form (2NF) if it is in 1NF and has no:",
    options: ["Transitive dependencies", "Partial functional dependencies of non-prime attributes", "Multi-valued dependencies", "Join dependencies"],
    correctOptionIndex: 1,
    explanation: "2NF eliminates partial dependencies where a non-prime attribute depends on only part of a composite candidate key.",
  },
  {
    id: "dbms-13",
    topic: "DBMS",
    subtopic: "SQL Joins",
    difficultyLabel: "Medium",
    difficultyLevel: 3,
    questionText: "Which JOIN operation returns all rows from the left table and matched rows from the right table?",
    options: ["INNER JOIN", "RIGHT OUTER JOIN", "LEFT OUTER JOIN", "FULL OUTER JOIN"],
    correctOptionIndex: 2,
    explanation: "LEFT OUTER JOIN includes every row from the left table; unmatched right table columns return NULL.",
  },
  {
    id: "dbms-14",
    topic: "DBMS",
    subtopic: "Indexing",
    difficultyLabel: "Medium",
    difficultyLevel: 3,
    questionText: "Why are B+ Trees preferred over B Trees for relational database indexing?",
    options: [
      "B+ Trees hold data pointers in leaf nodes only, allowing higher node fanout and linked leaf sequential traversal",
      "B+ Trees have fewer levels than B Trees for small datasets",
      "B+ Trees eliminate binary search overhead",
      "B+ Trees do not require rebalancing"
    ],
    correctOptionIndex: 0,
    explanation: "B+ trees store data pointers exclusively at leaf nodes. Internal nodes hold keys only, maxing fanout and enabling fast sequential leaf scans.",
  },
  {
    id: "dbms-15",
    topic: "DBMS",
    subtopic: "Indexing",
    difficultyLabel: "Medium",
    difficultyLevel: 3,
    questionText: "Adding secondary indexes to a database table generally improves:",
    options: ["INSERT speed", "UPDATE speed", "SELECT query speed", "DELETE speed"],
    correctOptionIndex: 2,
    explanation: "Indexes speed up read queries (SELECT) via quick lookup trees, but add overhead to write operations (INSERT/UPDATE/DELETE).",
  },
  {
    id: "dbms-16",
    topic: "DBMS",
    subtopic: "Concurrency Control",
    difficultyLabel: "Medium",
    difficultyLevel: 3,
    questionText: "A 'Dirty Read' anomaly occurs when a transaction:",
    options: [
      "Reads data that has been modified by an uncommitted transaction",
      "Reads different values for the same row within one transaction",
      "Is blocked by a deadlocked resource",
      "Overwrites another transaction's committed write"
    ],
    correctOptionIndex: 0,
    explanation: "A dirty read occurs when Transaction A reads modifications made by Transaction B before B commits or rolls back.",
  },
  {
    id: "dbms-17",
    topic: "DBMS",
    subtopic: "Relational Algebra",
    difficultyLabel: "Medium",
    difficultyLevel: 3,
    questionText: "In Relational Algebra, which operator projects specified columns from a relation?",
    options: ["Sigma (σ)", "Pi (π)", "Rho (ρ)", "Gamma (γ)"],
    correctOptionIndex: 1,
    explanation: "The projection operator Pi (π) selects specified attributes (columns) from a relation schema.",
  },
  {
    id: "dbms-18",
    topic: "DBMS",
    subtopic: "Relational Algebra",
    difficultyLabel: "Medium",
    difficultyLevel: 3,
    questionText: "In Relational Algebra, which operator selects tuples (rows) satisfying a predicate?",
    options: ["Pi (π)", "Sigma (σ)", "Theta (θ)", "Delta (δ)"],
    correctOptionIndex: 1,
    explanation: "The selection operator Sigma (σ) filters rows satisfying a predicate condition.",
  },
  {
    id: "dbms-19",
    topic: "DBMS",
    subtopic: "Transactions",
    difficultyLabel: "Medium",
    difficultyLevel: 3,
    questionText: "Conflict Serializability of a transaction schedule can be checked using:",
    options: ["Precedence (Serialization) Graph cycle detection", "Wait-for graph", "B+ Tree depth", "2PL phase timer"],
    correctOptionIndex: 0,
    explanation: "A schedule is conflict serializable if and only if its Precedence Graph has no directed cycles.",
  },
  {
    id: "dbms-20",
    topic: "DBMS",
    subtopic: "Normalization",
    difficultyLabel: "Hard",
    difficultyLevel: 4,
    questionText: "A decomposition of schema R into R1 and R2 is Lossless-Join if and only if:",
    options: [
      "(R1 ∩ R2) → R1 or (R1 ∩ R2) → R2",
      "(R1 ∪ R2) = R",
      "R1 and R2 share no common attributes",
      "Both R1 and R2 are in BCNF"
    ],
    correctOptionIndex: 0,
    explanation: "Lossless join decomposition requires the common attributes (R1 ∩ R2) to form a superkey for at least one of the decomposed schemas.",
  },
  {
    id: "dbms-21",
    topic: "DBMS",
    subtopic: "Normalization",
    difficultyLabel: "Hard",
    difficultyLevel: 4,
    questionText: "Which decomposition property is NOT guaranteed when decomposing a relation schema into BCNF?",
    options: ["Lossless join", "Dependency preservation", "Redundancy reduction", "1NF compliance"],
    correctOptionIndex: 1,
    explanation: "Decomposing into BCNF always guarantees lossless join, but may not preserve functional dependencies (unlike 3NF).",
  },
  {
    id: "dbms-22",
    topic: "DBMS",
    subtopic: "Transactions",
    difficultyLabel: "Hard",
    difficultyLevel: 4,
    questionText: "Which ANSI SQL isolation level prevents Phantom Reads?",
    options: ["Read Uncommitted", "Read Committed", "Repeatable Read", "Serializable"],
    correctOptionIndex: 3,
    explanation: "Serializable isolation level prevents dirty reads, non-repeatable reads, and phantom reads using range locks or MVCC snapshots.",
  },
  {
    id: "dbms-23",
    topic: "DBMS",
    subtopic: "Crash Recovery",
    difficultyLabel: "Hard",
    difficultyLevel: 4,
    questionText: "The Write-Ahead Logging (WAL) protocol requires that:",
    options: [
      "Log records must be written to stable storage BEFORE dirty database pages are written to disk",
      "Database pages must be flushed immediately after every SQL query",
      "No log record is created until transaction commits",
      "Checkpoints happen only when disk is full"
    ],
    correctOptionIndex: 0,
    explanation: "WAL dictates that log updates describing database changes must reach non-volatile disk storage before data pages are flushed.",
  },
  {
    id: "dbms-24",
    topic: "DBMS",
    subtopic: "Crash Recovery",
    difficultyLabel: "Hard",
    difficultyLevel: 4,
    questionText: "In the ARIES recovery algorithm, which phase scans the log forward from checkpoint to reconstruct state at system crash time?",
    options: ["Analysis Phase", "Redo Phase", "Undo Phase", "Checkpoint Phase"],
    correctOptionIndex: 1,
    explanation: "The Redo Phase scans forward from a calculated point to reapply all updates (repeating history) up to crash time.",
  },
  {
    id: "dbms-25",
    topic: "DBMS",
    subtopic: "Indexing",
    difficultyLabel: "Hard",
    difficultyLevel: 4,
    questionText: "In a B+ Tree with node order m (maximum m pointers per internal node), the minimum number of keys in a non-root internal node is:",
    options: ["1", "⌈m / 2⌉ - 1", "m - 1", "⌈m / 2⌉"],
    correctOptionIndex: 1,
    explanation: "Every non-root node in a B+ Tree of order m must have at least ⌈m/2⌉ pointers, which corresponds to ⌈m/2⌉ - 1 keys.",
  },
  {
    id: "dbms-26",
    topic: "DBMS",
    subtopic: "Normalization",
    difficultyLabel: "Hard",
    difficultyLevel: 4,
    questionText: "Fourth Normal Form (4NF) addresses anomalies caused by:",
    options: ["Transitive dependencies", "Partial dependencies", "Multi-valued dependencies (MVDs)", "Join dependencies"],
    correctOptionIndex: 2,
    explanation: "4NF extends BCNF by ensuring that non-trivial multi-valued dependencies (X ↠ Y) exist only when X is a superkey.",
  },
  {
    id: "dbms-27",
    topic: "DBMS",
    subtopic: "Distributed Databases",
    difficultyLabel: "Very Hard",
    difficultyLevel: 5,
    questionText: "In Two-Phase Commit (2PC) protocol, if a participant node votes VOTE-ABORT during Phase 1 (Prepare):",
    options: [
      "The coordinator sends GLOBAL-ABORT to all participant nodes",
      "The coordinator overrides and sends GLOBAL-COMMIT",
      "The participant retries the vote 3 times",
      "The transaction enters limbo state"
    ],
    correctOptionIndex: 0,
    explanation: "2PC requires unanimous VOTE-COMMIT from all nodes. A single VOTE-ABORT forces the coordinator to issue GLOBAL-ABORT.",
  },
  {
    id: "dbms-28",
    topic: "DBMS",
    subtopic: "Query Optimization",
    difficultyLabel: "Very Hard",
    difficultyLevel: 5,
    questionText: "In Query Optimization, pushing selection (σ) down relational algebra trees is beneficial because:",
    options: [
      "It reduces the size of intermediate relations before costly join operations",
      "It transforms left-deep trees into right-deep trees",
      "It eliminates primary key constraints",
      "It replaces nested loop joins with hash joins"
    ],
    correctOptionIndex: 0,
    explanation: "Evaluating selections early filters out non-matching tuples, drastically minimizing intermediate tuple counts input to subsequent joins.",
  },
  {
    id: "dbms-29",
    topic: "DBMS",
    subtopic: "Concurrency Control",
    difficultyLabel: "Very Hard",
    difficultyLevel: 5,
    questionText: "Multi-Version Concurrency Control (MVCC) achieves lock-free read consistency by:",
    options: [
      "Providing each read transaction a point-in-time snapshot of committed data versions",
      "Acquiring exclusive locks on every read operation",
      "Converting SQL queries to C++ compiled binaries",
      "Executing transactions serially on a single core"
    ],
    correctOptionIndex: 0,
    explanation: "MVCC maintains multiple versions of data rows, allowing readers to read a consistent snapshot without blocking concurrent writers.",
  },
  {
    id: "dbms-30",
    topic: "DBMS",
    subtopic: "Distributed Systems",
    difficultyLabel: "Very Hard",
    difficultyLevel: 5,
    questionText: "According to the CAP Theorem for distributed data stores, during a network partition (P), a system can guarantee at most:",
    options: ["Consistency or Availability", "Consistency and Availability", "Durability and Isolation", "Atomicity and Serializability"],
    correctOptionIndex: 0,
    explanation: "CAP states that in the presence of a Network Partition (P), a system must trade off between Consistency (C) and Availability (A).",
  },

  // ── OS (30 Questions) ───────────────────────────────────────────────────────
  {
    id: "os-1",
    topic: "OS",
    subtopic: "Basics",
    difficultyLabel: "Easy",
    difficultyLevel: 1,
    questionText: "Which of the following is NOT a function of an Operating System?",
    options: ["Memory management", "Process scheduling", "Compiling source code", "File system management"],
    correctOptionIndex: 2,
    explanation: "Compiling source code is the job of a compiler, not the OS. The OS manages hardware resources, processes, memory, and files.",
  },
  {
    id: "os-2",
    topic: "OS",
    subtopic: "Scheduling",
    difficultyLabel: "Easy",
    difficultyLevel: 2,
    questionText: "In Round-Robin CPU scheduling, what determines the context switch frequency?",
    options: ["Process priority", "Memory size", "Time quantum", "Number of CPU cores"],
    correctOptionIndex: 2,
    explanation: "Round-Robin assigns each process a fixed time quantum. When it expires, the CPU switches to the next process regardless of completion.",
  },
  {
    id: "os-3",
    topic: "OS",
    subtopic: "Process Synchronization",
    difficultyLabel: "Medium",
    difficultyLevel: 3,
    questionText: "Which condition is NOT required for a deadlock to occur?",
    options: ["Mutual Exclusion", "Hold and Wait", "Preemption Enabled", "Circular Wait"],
    correctOptionIndex: 2,
    explanation: "Deadlock requires No Preemption (resources cannot be forcibly taken). If preemption is enabled, resources can be reclaimed, preventing deadlock.",
  },
  {
    id: "os-4",
    topic: "OS",
    subtopic: "Virtual Memory",
    difficultyLabel: "Hard",
    difficultyLevel: 4,
    questionText: "Which page replacement algorithm suffers from Belady's Anomaly?",
    options: ["LRU", "FIFO", "Optimal (OPT)", "Second Chance (Clock)"],
    correctOptionIndex: 1,
    explanation: "FIFO can produce more page faults when the number of frames increases — this counterintuitive behavior is called Belady's Anomaly.",
  },
  {
    id: "os-5",
    topic: "OS",
    subtopic: "Memory Management",
    difficultyLabel: "Very Hard",
    difficultyLevel: 5,
    questionText: "In a segmented-paging memory model, a logical address is typically resolved through:",
    options: [
      "Direct mapping via a single-level page table",
      "Segment table → page table → physical frame",
      "Inverted page table only",
      "Base register addition only"
    ],
    correctOptionIndex: 1,
    explanation: "In segmented-paging, the segment table locates the page table for the segment, which then maps the page number to a physical frame plus offset.",
  },
  {
    id: "os-6",
    topic: "OS",
    subtopic: "Process Management",
    difficultyLabel: "Easy",
    difficultyLevel: 1,
    questionText: "Where is the state of a process (registers, program counter, PID) maintained by the OS kernel?",
    options: ["Process Control Block (PCB)", "Page Table", "Inode Table", "Segment Table"],
    correctOptionIndex: 0,
    explanation: "The PCB (Process Control Block) is the data structure storing process state, program counter, registers, and CPU scheduling info.",
  },
  {
    id: "os-7",
    topic: "OS",
    subtopic: "Architecture",
    difficultyLabel: "Easy",
    difficultyLevel: 1,
    questionText: "User applications execute in which CPU execution mode?",
    options: ["Kernel Mode", "User Mode", "Supervisor Mode", "Hypervisor Mode"],
    correctOptionIndex: 1,
    explanation: "User Mode restricts access to privileged hardware instructions to protect system stability.",
  },
  {
    id: "os-8",
    topic: "OS",
    subtopic: "CPU Scheduling",
    difficultyLabel: "Easy",
    difficultyLevel: 2,
    questionText: "Which CPU scheduling algorithm gives the minimum average waiting time for a given set of processes?",
    options: ["First-Come, First-Served (FCFS)", "Shortest Job First (SJF)", "Round Robin (RR)", "Priority Scheduling"],
    correctOptionIndex: 1,
    explanation: "SJF (Shortest Job First) is mathematically optimal for minimizing average waiting time.",
  },
  {
    id: "os-9",
    topic: "OS",
    subtopic: "Process States",
    difficultyLabel: "Easy",
    difficultyLevel: 2,
    questionText: "When a running process makes an I/O system call, its state changes from Running to:",
    options: ["Ready", "Waiting (Blocked)", "Terminated", "Suspended"],
    correctOptionIndex: 1,
    explanation: "Processes awaiting I/O completion enter the Waiting (Blocked) state until I/O finishes.",
  },
  {
    id: "os-10",
    topic: "OS",
    subtopic: "Threads",
    difficultyLabel: "Easy",
    difficultyLevel: 2,
    questionText: "Threads belonging to the same process share which memory section?",
    options: ["Register values", "Stack memory", "Heap and global variables", "Thread ID"],
    correctOptionIndex: 2,
    explanation: "Threads of a process share code section, data section (heap/globals), and OS resources, but maintain separate stacks and registers.",
  },
  {
    id: "os-11",
    topic: "OS",
    subtopic: "Synchronization",
    difficultyLabel: "Medium",
    difficultyLevel: 3,
    questionText: "A counting semaphore initialized to value 5 allows how many processes into the critical section simultaneously?",
    options: ["1", "5", "0", "Unlimited"],
    correctOptionIndex: 1,
    explanation: "Counting semaphores permit access up to their initial non-negative integer value (5).",
  },
  {
    id: "os-12",
    topic: "OS",
    subtopic: "Deadlocks",
    difficultyLabel: "Medium",
    difficultyLevel: 3,
    questionText: "Banker's Algorithm is used for deadlock:",
    options: ["Detection", "Prevention", "Avoidance", "Recovery"],
    correctOptionIndex: 2,
    explanation: "Banker's algorithm performs safety checks on resource requests to avoid entering unsafe states.",
  },
  {
    id: "os-13",
    topic: "OS",
    subtopic: "Memory Management",
    difficultyLabel: "Medium",
    difficultyLevel: 3,
    questionText: "Paging avoids external fragmentation, but can cause:",
    options: ["Internal fragmentation", "Segment fault", "Thrashing", "Deadlock"],
    correctOptionIndex: 0,
    explanation: "Fixed-size page frames avoid external fragmentation but may leave unused bytes in the last page frame (internal fragmentation).",
  },
  {
    id: "os-14",
    topic: "OS",
    subtopic: "Memory Management",
    difficultyLabel: "Medium",
    difficultyLevel: 3,
    questionText: "Segmentation allocates memory in variable-size segments, which can lead to:",
    options: ["Internal fragmentation", "External fragmentation", "TLB miss", "Page fault"],
    correctOptionIndex: 1,
    explanation: "Variable-size segments leave scattered free memory holes across physical RAM over time (external fragmentation).",
  },
  {
    id: "os-15",
    topic: "OS",
    subtopic: "Virtual Memory",
    difficultyLabel: "Medium",
    difficultyLevel: 3,
    questionText: "The Translation Lookaside Buffer (TLB) is a fast hardware cache used to store:",
    options: ["Disk sector locations", "Page table entries (page-to-frame mappings)", "Process control blocks", "File system inodes"],
    correctOptionIndex: 1,
    explanation: "TLB caches recent virtual page to physical frame translations to accelerate address translation.",
  },
  {
    id: "os-16",
    topic: "OS",
    subtopic: "Disk Scheduling",
    difficultyLabel: "Medium",
    difficultyLevel: 3,
    questionText: "Which disk scheduling algorithm moves the disk arm from one end of the disk to the other, servicing requests along the way (Elevator Algorithm)?",
    options: ["FCFS", "SSTF (Shortest Seek Time First)", "SCAN", "C-LOOK"],
    correctOptionIndex: 2,
    explanation: "The SCAN algorithm sweeps back and forth across disk cylinders servicing pending I/O requests.",
  },
  {
    id: "os-17",
    topic: "OS",
    subtopic: "Process Management",
    difficultyLabel: "Medium",
    difficultyLevel: 3,
    questionText: "In UNIX, what value does the fork() system call return to the parent process upon successful execution?",
    options: ["0", "Child process PID (>0)", "-1", "1"],
    correctOptionIndex: 1,
    explanation: "fork() returns 0 to the child process and the child's new PID (>0) to the parent process.",
  },
  {
    id: "os-18",
    topic: "OS",
    subtopic: "Process Management",
    difficultyLabel: "Medium",
    difficultyLevel: 3,
    questionText: "Overhead associated with Context Switching includes saving and restoring:",
    options: ["CPU registers, program counter, and switching memory context", "Hard disk partition table", "Network IP routing cache", "Compiler symbol table"],
    correctOptionIndex: 0,
    explanation: "Context switching stores current process registers and program counter into its PCB and restores another process state.",
  },
  {
    id: "os-19",
    topic: "OS",
    subtopic: "Virtual Memory",
    difficultyLabel: "Medium",
    difficultyLevel: 3,
    questionText: "Thrashing occurs in virtual memory systems when:",
    options: [
      "CPU utilization is 100%",
      "The system spends more time swapping pages in and out than executing instructions",
      "Hard disk crashes due to high temperature",
      "Process count drops to zero"
    ],
    correctOptionIndex: 1,
    explanation: "Thrashing happens when the total working set size of active processes exceeds available physical memory, forcing continuous page faults.",
  },
  {
    id: "os-20",
    topic: "OS",
    subtopic: "Virtual Memory",
    difficultyLabel: "Hard",
    difficultyLevel: 4,
    questionText: "What is the primary advantage of an Inverted Page Table compared to standard multi-level page tables?",
    options: [
      "Page lookup time is O(1) without hash table",
      "Memory space required for page table is proportional to physical RAM size rather than virtual address space size",
      "Eliminates TLB miss completely",
      "Allows infinite virtual address range"
    ],
    correctOptionIndex: 1,
    explanation: "Inverted page tables have one entry per physical page frame, dramatically shrinking page table memory overhead in 64-bit architectures.",
  },
  {
    id: "os-21",
    topic: "OS",
    subtopic: "Synchronization",
    difficultyLabel: "Hard",
    difficultyLevel: 4,
    questionText: "Peterson's Algorithm for 2-process critical section synchronization guarantees:",
    options: [
      "Mutual exclusion, progress, and bounded waiting",
      "Hardware atomic instructions only",
      "Deadlock handling via timeout",
      "Priority inheritance"
    ],
    correctOptionIndex: 0,
    explanation: "Peterson's software solution satisfies all three requirements: Mutual Exclusion, Progress, and Bounded Waiting.",
  },
  {
    id: "os-22",
    topic: "OS",
    subtopic: "Synchronization",
    difficultyLabel: "Hard",
    difficultyLevel: 4,
    questionText: "How does a Monitor differ from a Semaphore?",
    options: [
      "A Monitor is a high-level language construct that enforces mutual exclusion automatically inside its methods",
      "Monitors run in hardware while semaphores run in user space",
      "Semaphores can only be used by 1 thread",
      "Monitors cannot have condition variables"
    ],
    correctOptionIndex: 0,
    explanation: "Monitors encapsulate shared data and operations; compiler/runtime guarantees only one thread executes a monitor method at a time.",
  },
  {
    id: "os-23",
    topic: "OS",
    subtopic: "CPU Scheduling",
    difficultyLabel: "Hard",
    difficultyLevel: 4,
    questionText: "Multilevel Feedback Queue (MLFQ) scheduling dynamically adjusts process priority based on:",
    options: ["CPU burst behavior (I/O-bound vs CPU-bound)", "File system storage size", "User account privileges", "Network bandwidth usage"],
    correctOptionIndex: 0,
    explanation: "MLFQ moves processes between queues based on CPU usage: I/O-bound processes stay at high priority; CPU-intensive processes decay to lower queues.",
  },
  {
    id: "os-24",
    topic: "OS",
    subtopic: "Storage Systems",
    difficultyLabel: "Hard",
    difficultyLevel: 4,
    questionText: "In RAID 5 configuration across N disks, the storage capacity available for data is equivalent to:",
    options: ["N disks", "(N - 1) disks", "N / 2 disks", "1 disk"],
    correctOptionIndex: 1,
    explanation: "RAID 5 striping distributes block-level parity across all N disks, using 1 disk equivalent space for parity protection.",
  },
  {
    id: "os-25",
    topic: "OS",
    subtopic: "File Systems",
    difficultyLabel: "Hard",
    difficultyLevel: 4,
    questionText: "In a classic UNIX inode containing 12 direct block pointers, 1 single indirect pointer, 1 double indirect pointer, and 1 triple indirect pointer (block size 4 KB, block pointer 4 bytes):",
    options: [
      "Direct pointers can address up to 48 KB directly",
      "Single indirect pointer can address up to 1 MB",
      "Double indirect pointer can address up to 4 GB",
      "All of the above"
    ],
    correctOptionIndex: 0,
    explanation: "12 direct pointers × 4 KB = 48 KB file data addressed directly without indirect disk access.",
  },
  {
    id: "os-26",
    topic: "OS",
    subtopic: "Real-Time OS",
    difficultyLabel: "Hard",
    difficultyLevel: 4,
    questionText: "In Earliest Deadline First (EDF) real-time scheduling, priorities are assigned:",
    options: [
      "Dynamically based on whichever active task has the closest deadline",
      "Statically based on task period (Rate Monotonic)",
      "Randomly among ready tasks",
      "Based on total execution time"
    ],
    correctOptionIndex: 0,
    explanation: "EDF is a dynamic priority algorithm where the task nearest its deadline gets highest priority.",
  },
  {
    id: "os-27",
    topic: "OS",
    subtopic: "Security & CPU",
    difficultyLabel: "Very Hard",
    difficultyLevel: 5,
    questionText: "Kernel Page-Table Isolation (KPTI) was introduced to mitigate which speculative execution CPU vulnerability?",
    options: ["Meltdown", "Buffer Overflow", "Rowhammer", "SQL Injection"],
    correctOptionIndex: 0,
    explanation: "KPTI separates user space and kernel space page tables to prevent the Meltdown speculative execution flaw from reading kernel memory.",
  },
  {
    id: "os-28",
    topic: "OS",
    subtopic: "Hardware Interaction",
    difficultyLabel: "Very Hard",
    difficultyLevel: 5,
    questionText: "On a Non-Uniform Memory Access (NUMA) architecture, OS thread schedulers strive to maintain:",
    options: [
      "NUMA Node Affinity (executing threads on the CPU core local to their allocated memory node)",
      "Uniform Round-Robin thread migration across all sockets",
      "Centralized single-socket locking",
      "Complete disabling of L3 cache"
    ],
    correctOptionIndex: 0,
    explanation: "NUMA-aware scheduling keeps threads on the local socket where their memory pages reside to avoid remote bus latency.",
  },
  {
    id: "os-29",
    topic: "OS",
    subtopic: "Kernel Internals",
    difficultyLabel: "Very Hard",
    difficultyLevel: 5,
    questionText: "The Linux Completely Fair Scheduler (CFS) tracks virtual runtime (vruntime) and selects the next task to run using which data structure?",
    options: ["Red-Black Tree", "FIFO Queue", "Hash Map", "Binary Heap"],
    correctOptionIndex: 0,
    explanation: "CFS uses a self-balancing Red-Black tree ordered by `vruntime` to pick the leftmost node (smallest vruntime) in O(log N) time.",
  },
  {
    id: "os-30",
    topic: "OS",
    subtopic: "Memory Management",
    difficultyLabel: "Very Hard",
    difficultyLevel: 5,
    questionText: "How does Copy-on-Write (COW) optimize process creation via fork()?",
    options: [
      "Parent and child share physical pages marked read-only until either process attempts to write to a page",
      "Copies all physical pages immediately during fork()",
      "Stores child memory on swap disk",
      "Executes child in parent's call stack"
    ],
    correctOptionIndex: 0,
    explanation: "COW delays copying memory pages during fork(). Pages are shared read-only; physical copies are made only when a page write occurs.",
  },

  // ── CN (30 Questions) ───────────────────────────────────────────────────────
  {
    id: "cn-1",
    topic: "CN",
    subtopic: "Basics",
    difficultyLabel: "Easy",
    difficultyLevel: 1,
    questionText: "Which layer of the OSI model is responsible for end-to-end communication between applications?",
    options: ["Network Layer", "Data Link Layer", "Transport Layer", "Physical Layer"],
    correctOptionIndex: 2,
    explanation: "The Transport Layer (Layer 4) provides end-to-end communication, segmentation, error recovery, and flow control via TCP or UDP.",
  },
  {
    id: "cn-2",
    topic: "CN",
    subtopic: "IP Addressing",
    difficultyLabel: "Easy",
    difficultyLevel: 2,
    questionText: "How many bits are in an IPv4 address?",
    options: ["16 bits", "32 bits", "64 bits", "128 bits"],
    correctOptionIndex: 1,
    explanation: "IPv4 addresses are 32 bits long, written as four 8-bit octets in dotted-decimal notation (e.g., 192.168.1.1).",
  },
  {
    id: "cn-3",
    topic: "CN",
    subtopic: "Transport Protocols",
    difficultyLabel: "Medium",
    difficultyLevel: 3,
    questionText: "What triggers TCP's Fast Retransmit algorithm?",
    options: [
      "Three duplicate ACKs received",
      "Retransmission timeout (RTO) expiry",
      "Window size dropping to 1 MSS",
      "TCP SYN re-synchronization"
    ],
    correctOptionIndex: 0,
    explanation: "Fast Retransmit is triggered when the sender receives 3 duplicate ACKs, indicating packet loss without waiting for the RTO timer to expire.",
  },
  {
    id: "cn-4",
    topic: "CN",
    subtopic: "Routing",
    difficultyLabel: "Hard",
    difficultyLevel: 4,
    questionText: "Which routing protocol uses the Bellman-Ford algorithm and is limited to 15 hops?",
    options: ["OSPF", "BGP", "RIP", "EIGRP"],
    correctOptionIndex: 2,
    explanation: "RIP (Routing Information Protocol) uses distance-vector routing based on Bellman-Ford with a maximum hop count of 15 to prevent routing loops.",
  },
  {
    id: "cn-5",
    topic: "CN",
    subtopic: "Congestion Control",
    difficultyLabel: "Very Hard",
    difficultyLevel: 5,
    questionText: "In TCP CUBIC congestion control, after a packet loss event, the congestion window (cwnd) is set to:",
    options: [
      "Half of the current cwnd (multiplicative decrease)",
      "1 MSS (restart from slow start)",
      "A fixed value unrelated to current cwnd",
      "ssthresh remains unchanged"
    ],
    correctOptionIndex: 0,
    explanation: "TCP CUBIC uses multiplicative decrease: after loss, cwnd is multiplied by a factor β (typically 0.7), then CUBIC growth resumes from that point.",
  },
  {
    id: "cn-6",
    topic: "CN",
    subtopic: "Protocols",
    difficultyLabel: "Easy",
    difficultyLevel: 1,
    questionText: "What are the default port numbers for HTTP and HTTPS protocols?",
    options: ["21 and 22", "80 and 443", "25 and 110", "53 and 67"],
    correctOptionIndex: 1,
    explanation: "HTTP operates on port 80; HTTPS operates securely over TLS on port 443.",
  },
  {
    id: "cn-7",
    topic: "CN",
    subtopic: "Data Link Layer",
    difficultyLabel: "Easy",
    difficultyLevel: 1,
    questionText: "What is the length of an Ethernet MAC address in bits?",
    options: ["32 bits", "48 bits", "64 bits", "128 bits"],
    correctOptionIndex: 1,
    explanation: "A MAC (Media Access Control) address is a 48-bit (6-byte) hardware identifier assigned to network interfaces.",
  },
  {
    id: "cn-8",
    topic: "CN",
    subtopic: "Network Layer Protocols",
    difficultyLabel: "Easy",
    difficultyLevel: 2,
    questionText: "Which protocol resolves a known IPv4 address to its corresponding physical MAC address on a local network?",
    options: ["DNS", "DHCP", "ARP", "ICMP"],
    correctOptionIndex: 2,
    explanation: "ARP (Address Resolution Protocol) maps 32-bit IP addresses to 48-bit hardware MAC addresses on local Ethernet segments.",
  },
  {
    id: "cn-9",
    topic: "CN",
    subtopic: "Network Layer Protocols",
    difficultyLabel: "Easy",
    difficultyLevel: 2,
    questionText: "The `ping` diagnostic utility uses which network protocol?",
    options: ["TCP", "UDP", "ICMP", "IGMP"],
    correctOptionIndex: 2,
    explanation: "Ping sends ICMP Echo Request packets and listens for ICMP Echo Reply packets.",
  },
  {
    id: "cn-10",
    topic: "CN",
    subtopic: "Application Layer",
    difficultyLabel: "Easy",
    difficultyLevel: 2,
    questionText: "What is the primary role of the Domain Name System (DNS)?",
    options: [
      "Translating domain names (e.g. google.com) into IP addresses",
      "Encrypting web traffic",
      "Assigning dynamic IP addresses to client hosts",
      "Routing packets across WAN backbones"
    ],
    correctOptionIndex: 0,
    explanation: "DNS acts as the Internet's directory, translating human-readable hostnames into numerical IP addresses.",
  },
  {
    id: "cn-11",
    topic: "CN",
    subtopic: "Transport Protocols",
    difficultyLabel: "Medium",
    difficultyLevel: 3,
    questionText: "Which packet sequence establishes a TCP connection (3-way handshake)?",
    options: ["SYN → SYN-ACK → ACK", "ACK → SYN → ACK", "FIN → ACK → FIN-ACK", "CONNECT → ACCEPT → OK"],
    correctOptionIndex: 0,
    explanation: "TCP 3-way handshake sequence is Client SYN → Server SYN-ACK → Client ACK.",
  },
  {
    id: "cn-12",
    topic: "CN",
    subtopic: "Transport Layer",
    difficultyLabel: "Medium",
    difficultyLevel: 3,
    questionText: "Why is UDP preferred over TCP for real-time video streaming and gaming?",
    options: [
      "UDP has lower overhead without connection setup latency or retransmission delays",
      "UDP encrypts packet payloads automatically",
      "UDP guarantees in-order packet delivery",
      "UDP supports unlimited packet size"
    ],
    correctOptionIndex: 0,
    explanation: "UDP is connectionless and header-light without retransmission delays, prioritizing timely delivery over perfect reliability.",
  },
  {
    id: "cn-13",
    topic: "CN",
    subtopic: "IP Subnetting",
    difficultyLabel: "Medium",
    difficultyLevel: 3,
    questionText: "How many usable host IP addresses are available in a standard /24 IPv4 subnet?",
    options: ["256", "254", "255", "128"],
    correctOptionIndex: 1,
    explanation: "A /24 subnet has 8 host bits (2⁸ = 256 addresses). Subtracting network ID and broadcast address leaves 254 usable host IPs.",
  },
  {
    id: "cn-14",
    topic: "CN",
    subtopic: "Application Layer Protocols",
    difficultyLabel: "Medium",
    difficultyLevel: 3,
    questionText: "What is the 4-step message exchange sequence for DHCP IP allocation?",
    options: ["Discover → Offer → Request → Acknowledge (DORA)", "Request → Grant → Verify → Confirm", "SYN → ACK → DATA → CLOSE", "Query → Response → Accept → Done"],
    correctOptionIndex: 0,
    explanation: "DHCP allocation follows DORA: DHCPDiscover → DHCPOffer → DHCPRequest → DHCPPack (Acknowledge).",
  },
  {
    id: "cn-15",
    topic: "CN",
    subtopic: "Data Link Protocols",
    difficultyLabel: "Medium",
    difficultyLevel: 3,
    questionText: "In Sliding Window flow control, how does Go-Back-N handle a damaged/lost frame compared to Selective Repeat?",
    options: [
      "Go-Back-N retransmits all frames from the lost frame onward; Selective Repeat retransmits only the lost frame",
      "Selective Repeat discards all subsequent frames",
      "Go-Back-N requires receiver buffers for out-of-order frames",
      "Both protocols behave identically"
    ],
    correctOptionIndex: 0,
    explanation: "Go-Back-N discards out-of-order frames and forces resending the entire window. Selective Repeat buffers out-of-order frames and retransmits only missing ones.",
  },
  {
    id: "cn-16",
    topic: "CN",
    subtopic: "Network Devices",
    difficultyLabel: "Medium",
    difficultyLevel: 3,
    questionText: "At which layer of the OSI model does a standard Layer 2 Ethernet Switch operate?",
    options: ["Physical Layer (Layer 1)", "Data Link Layer (Layer 2)", "Network Layer (Layer 3)", "Transport Layer (Layer 4)"],
    correctOptionIndex: 1,
    explanation: "Standard Ethernet switches operate at Layer 2, forwarding frames using MAC address tables.",
  },
  {
    id: "cn-17",
    topic: "CN",
    subtopic: "Network Layer",
    difficultyLabel: "Medium",
    difficultyLevel: 3,
    questionText: "Network Address Translation (NAT) enables multiple hosts on a private LAN to share:",
    options: ["A single public IPv4 address via port mapping (PAT)", "A single MAC address", "A single DNS server", "A single Wi-Fi channel"],
    correctOptionIndex: 0,
    explanation: "NAT/PAT maps internal private IP address and port combinations to a single external public IP address.",
  },
  {
    id: "cn-18",
    topic: "CN",
    subtopic: "Data Link Layer",
    difficultyLabel: "Medium",
    difficultyLevel: 3,
    questionText: "CSMA/CD (Carrier Sense Multiple Access with Collision Detection) is used in half-duplex Ethernet to:",
    options: ["Listen before transmitting and abort transmission upon detecting a signal collision", "Allocate static time slots to hosts", "Encrypt frames over copper wires", "Perform IP routing"],
    correctOptionIndex: 0,
    explanation: "CSMA/CD senses bus activity, transmits when clear, listens for collisions, and sends jam signals if a collision occurs.",
  },
  {
    id: "cn-19",
    topic: "CN",
    subtopic: "Routing Protocols",
    difficultyLabel: "Medium",
    difficultyLevel: 3,
    questionText: "Border Gateway Protocol (BGP) is classified as which type of routing protocol?",
    options: ["Distance Vector Protocol", "Link State Protocol", "Path Vector Protocol", "Hybrid State Protocol"],
    correctOptionIndex: 2,
    explanation: "BGP is an Inter-Domain Path Vector protocol that exchanges AS-PATH attributes to route traffic between Autonomous Systems.",
  },
  {
    id: "cn-20",
    topic: "CN",
    subtopic: "Transport Protocols",
    difficultyLabel: "Hard",
    difficultyLevel: 4,
    questionText: "During TCP Congestion Control, what happens when `cwnd` reaches the `ssthresh` value?",
    options: [
      "TCP transitions from Slow Start (exponential growth) to Congestion Avoidance (linear growth)",
      "TCP drops `cwnd` to 1 MSS",
      "TCP closes the connection immediately",
      "TCP disables window scaling"
    ],
    correctOptionIndex: 0,
    explanation: "When cwnd = ssthresh, TCP switches from exponential Slow Start (+1 MSS per ACK) to linear Congestion Avoidance (+1 MSS per RTT).",
  },
  {
    id: "cn-21",
    topic: "CN",
    subtopic: "IP Addressing",
    difficultyLabel: "Hard",
    difficultyLevel: 4,
    questionText: "How many bits are in an IPv6 address?",
    options: ["32 bits", "64 bits", "128 bits", "256 bits"],
    correctOptionIndex: 2,
    explanation: "IPv6 addresses are 128 bits (16 bytes) long, represented in hexadecimal groups separated by colons.",
  },
  {
    id: "cn-22",
    topic: "CN",
    subtopic: "Security Protocols",
    difficultyLabel: "Hard",
    difficultyLevel: 4,
    questionText: "In TLS 1.2 Handshake, asymmetric key encryption (RSA or ECDHE) is used primarily to:",
    options: [
      "Encrypt all application data throughout the entire session",
      "Securely exchange a symmetric session key for fast data encryption",
      "Compress HTTP request headers",
      "Assign dynamic IP addresses"
    ],
    correctOptionIndex: 1,
    explanation: "Asymmetric cryptography is computationally heavy, so it is used during handshake to authenticate and negotiate symmetric session keys used for bulk data encryption.",
  },
  {
    id: "cn-23",
    topic: "CN",
    subtopic: "Routing Algorithms",
    difficultyLabel: "Hard",
    difficultyLevel: 4,
    questionText: "The 'Count-to-Infinity' problem in Distance Vector routing protocols (like RIP) is mitigated using:",
    options: ["Split Horizon with Poison Reverse", "Dijkstra algorithm", "Path MTU discovery", "BGP communities"],
    correctOptionIndex: 0,
    explanation: "Split Horizon prevents a router from advertising a route back to the neighbor from which it learned that route.",
  },
  {
    id: "cn-24",
    topic: "CN",
    subtopic: "Routing Protocols",
    difficultyLabel: "Hard",
    difficultyLevel: 4,
    questionText: "OSPF (Open Shortest Path First) uses which algorithm to compute shortest path tree for routing tables?",
    options: ["Bellman-Ford Algorithm", "Dijkstra's Algorithm", "Floyd-Warshall Algorithm", "Kruskal's Algorithm"],
    correctOptionIndex: 1,
    explanation: "OSPF is a Link-State protocol where every router floods link states and executes Dijkstra's algorithm.",
  },
  {
    id: "cn-25",
    topic: "CN",
    subtopic: "Application Protocols",
    difficultyLabel: "Hard",
    difficultyLevel: 4,
    questionText: "HTTP/2 introduces Multiplexing, which allows:",
    options: [
      "Concurrent request and response messages over a single TCP connection without head-of-line blocking at the HTTP layer",
      "Eliminating TCP connection setup",
      "Replacing DNS with IP hardcoding",
      "Bypassing TLS encryption"
    ],
    correctOptionIndex: 0,
    explanation: "HTTP/2 breaks requests/responses into binary frames, allowing multiple streams to interleave over one TCP connection.",
  },
  {
    id: "cn-26",
    topic: "CN",
    subtopic: "Transport Protocols",
    difficultyLabel: "Hard",
    difficultyLevel: 4,
    questionText: "The QUIC protocol (foundation for HTTP/3) runs over which transport protocol?",
    options: ["TCP", "UDP", "SCTP", "IP raw"],
    correctOptionIndex: 1,
    explanation: "QUIC operates over UDP to implement connection migration, built-in TLS 1.3, and independent streams without TCP HOL blocking.",
  },
  {
    id: "cn-27",
    topic: "CN",
    subtopic: "Advanced Transport",
    difficultyLabel: "Very Hard",
    difficultyLevel: 5,
    questionText: "The TCP Window Scaling option (RFC 1323) expands the maximum receive window size from 65,535 bytes up to:",
    options: ["1 Megabyte", "1 Gigabyte (2³⁰ bytes)", "16 Megabytes (2²⁴ bytes)", "512 Kilobytes"],
    correctOptionIndex: 1,
    explanation: "Window scaling specifies a 14-bit shift count, increasing max window size from 2¹⁶ - 1 to 2³⁰ bytes (1 GB) for high Bandwidth-Delay Product networks.",
  },
  {
    id: "cn-28",
    topic: "CN",
    subtopic: "Quality of Service",
    difficultyLabel: "Very Hard",
    difficultyLevel: 5,
    questionText: "In Differentiated Services (DiffServ QoS), packet priority is marked in the IPv4 header using which 6-bit field?",
    options: ["TTL (Time to Live)", "DSCP (Differentiated Services Code Point)", "Identification", "Fragment Offset"],
    correctOptionIndex: 1,
    explanation: "DSCP uses the first 6 bits of the Type of Service (ToS) byte in IPv4 (or Traffic Class in IPv6) to classify QoS per-hop behaviors.",
  },
  {
    id: "cn-29",
    topic: "CN",
    subtopic: "BGP Routing",
    difficultyLabel: "Very Hard",
    difficultyLevel: 5,
    questionText: "In internal BGP (iBGP), why are Route Reflectors used?",
    options: [
      "To avoid requiring a full mesh of iBGP TCP peerings between all routers in an Autonomous System",
      "To convert IPv4 routes into IPv6 routes",
      "To replace OSPF inside the AS",
      "To auto-generate MAC addresses"
    ],
    correctOptionIndex: 0,
    explanation: "iBGP split-horizon rule forbids re-advertising iBGP routes to other iBGP peers, requiring a full mesh O(N²) unless Route Reflectors are deployed.",
  },
  {
    id: "cn-30",
    topic: "CN",
    subtopic: "IP Layer",
    difficultyLabel: "Very Hard",
    difficultyLevel: 5,
    questionText: "In IPv4 packet fragmentation, the Fragment Offset field measures offset in units of:",
    options: ["1 byte", "4 bytes", "8 bytes (64 bits)", "16 bytes"],
    correctOptionIndex: 2,
    explanation: "The 13-bit Fragment Offset field measures payload offset in 8-byte blocks to accommodate up to 65,536 byte IP packets.",
  },
];

// ─── Admin Question Queue (for admin review page) ─────────────────────────────

export const MOCK_ADMIN_QUESTIONS: AdminQuestionItem[] = [
  {
    id: "q-gen-201",
    topic: "DBMS",
    subtopic: "Normalization",
    difficulty: "Medium",
    difficultyLevel: 3,
    questionText: "Which condition must be met for a relation schema R to be in Boyce-Codd Normal Form (BCNF)?",
    options: [
      "Every non-prime attribute is fully functionally dependent on the primary key.",
      "For every non-trivial functional dependency X → Y, X must be a superkey.",
      "There are no multi-valued dependencies in the relation.",
      "All foreign keys reference primary keys in valid relations."
    ],
    correctOptionIndex: 1,
    status: "pending",
    sourceLabel: "AI Generated Demo Question",
  },
  {
    id: "q-gen-202",
    topic: "OS",
    subtopic: "Virtual Memory",
    difficulty: "Hard",
    difficultyLevel: 4,
    questionText: "Which page replacement algorithm suffers from Belady's Anomaly where increasing frames leads to more page faults?",
    options: [
      "Least Recently Used (LRU)",
      "First-In, First-Out (FIFO)",
      "Optimal Page Replacement (OPT)",
      "Second Chance (Clock) Algorithm"
    ],
    correctOptionIndex: 1,
    status: "pending",
    sourceLabel: "AI Generated Demo Question",
  },
  {
    id: "q-gen-203",
    topic: "DSA",
    subtopic: "Graph Algorithms",
    difficulty: "Hard",
    difficultyLevel: 4,
    questionText: "What is the worst-case time complexity of Dijkstra's single-source shortest path algorithm using a Min-Heap priority queue?",
    options: ["O(V²)", "O((V + E) log V)", "O(V × E)", "O(E log E)"],
    correctOptionIndex: 1,
    status: "pending",
    sourceLabel: "AI Generated Demo Question",
  },
];

// Legacy alias for any references still using MOCK_ASSESSMENT_QUESTIONS
export const MOCK_ASSESSMENT_QUESTIONS = QUESTION_BANK;
